// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwlckyjzpvpfdkrdxqtf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53bGNreWp6cHZwZmRrcmR4cXRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExODAxMzUsImV4cCI6MjA3Njc1NjEzNX0.PEveqkWLTszZr965RBdxE3kMOf9scKEvGY9VhfJ5VvU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});